name: Survival_Cluster_Analysis
channels:
  - anaconda
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _tflow_select=2.3.0
  - absl-py=0.10.0
  - aiohttp=3.7.3
  - argon2-cffi=20.1.0
  - astor=0.8.1
  - astunparse=1.6.3
  - async-timeout=3.0.1
  - async_generator=1.10
  - backcall=0.2.0
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - blas=1.0
  - bleach=3.2.1
  - blinker=1.4
  - brotlipy=0.7.0
  - c-ares=1.17.1
  - ca-certificates=2021.5.25
  - cachetools=4.2.0
  - certifi=2021.5.30
  - cffi=1.14.4
  - chardet=3.0.4
  - click=7.1.2
  - cloudpickle=1.6.0
  - colorama=0.4.4
  - cryptography=3.3.1
  - cudatoolkit=11.0.221
  - cudnn=8.0.5.39
  - cycler=0.10.0
  - cytoolz=0.11.0
  - dask-core=2021.6.2
  - dbus=1.13.16
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fsspec=2021.6.0
  - gettext=0.19.8.1
  - glib=2.66.3
  - google-auth=1.23.0
  - google-auth-oauthlib=0.4.2
  - google-pasta=0.2.0
  - grpcio=1.34.1
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - hdf5=1.10.4
  - icu=58.2
  - idna=2.10
  - imageio=2.9.0
  - importlib-metadata=2.0.0
  - importlib_metadata=2.0.0
  - intel-openmp=2020.2
  - ipykernel=5.3.4
  - ipython=7.19.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.17.0
  - jinja2=2.11.2
  - joblib=0.17.0
  - jpeg=9b
  - jsonschema=3.2.0
  - jupyter=1.0.0
  - jupyter_client=6.1.7
  - jupyter_console=6.2.0
  - jupyter_core=4.7.0
  - jupyterlab_pygments=0.1.2
  - keras-applications=1.0.8
  - keras-preprocessing=1.1.2
  - kiwisolver=1.3.0
  - lcms2=2.11
  - ld_impl_linux-64=2.35.1
  - libblas=3.9.0
  - libcblas=3.9.0
  - libffi=3.2.1
  - libgcc-ng=9.3.0
  - libgfortran-ng=7.5.0
  - libgfortran4=7.5.0
  - libglib=2.66.3
  - libiconv=1.16
  - liblapack=3.9.0
  - libopenblas=0.3.12
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libsodium=1.0.18
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.9
  - llvm-openmp=11.0.1
  - locket=0.2.1
  - lz4-c=1.9.2
  - markdown=3.3.3
  - markupsafe=1.1.1
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - mistune=0.8.4
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - multidict=4.7.6
  - nbclient=0.5.1
  - nbconvert=6.0.7
  - nbformat=5.0.8
  - ncurses=6.2
  - nest-asyncio=1.4.3
  - networkx=2.5.1
  - notebook=6.1.4
  - numpy=1.19.2
  - numpy-base=1.19.2
  - oauthlib=3.1.0
  - olefile=0.46
  - openblas=0.3.12
  - openssl=1.1.1k
  - packaging=20.7
  - pandoc=2.11.3.2
  - pandocfilters=1.4.3
  - parso=0.8.1
  - partd=1.2.0
  - patsy=0.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=8.0.1
  - pip=20.2.4
  - prometheus_client=0.9.0
  - prompt-toolkit=3.0.8
  - prompt_toolkit=3.0.8
  - protobuf=3.13.0.1
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.20
  - pygments=2.7.3
  - pyjwt=1.7.1
  - pyopenssl=20.0.0
  - pyparsing=2.4.7
  - pyqt=5.9.2
  - pyrsistent=0.17.3
  - pysocks=1.7.1
  - python=3.8.5
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2020.4
  - pywavelets=1.1.1
  - pyzmq=20.0.0
  - qt=5.9.7
  - qtconsole=4.7.7
  - qtpy=1.9.0
  - readline=8.0
  - requests=2.25.0
  - requests-oauthlib=1.3.0
  - rsa=4.6
  - scikit-image=0.18.1
  - scipy=1.5.2
  - seaborn=0.11.0
  - seaborn-base=0.11.0
  - send2trash=1.5.0
  - setuptools=50.3.2
  - sip=4.19.13
  - six=1.15.0
  - sqlite=3.33.0
  - statsmodels=0.12.1
  - tensorboard-plugin-wit=1.6.0
  - tensorflow-estimator=2.5.0
  - termcolor=1.1.0
  - terminado=0.9.1
  - testpath=0.4.4
  - threadpoolctl=2.1.0
  - tifffile=2020.10.1
  - tk=8.6.10
  - toolz=0.11.1
  - tornado=6.1
  - traitlets=5.0.5
  - typing-extensions=3.7.4.3
  - typing_extensions=3.7.4.3
  - urllib3=1.25.11
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - werkzeug=1.0.1
  - wheel=0.36.0
  - widgetsnbextension=3.5.1
  - wrapt=1.12.1
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.5
  - yaml=0.2.5
  - yarl=1.5.1
  - zeromq=4.3.3
  - zipp=3.4.0
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - attrs==19.3.0
    - autograd==1.3
    - autograd-gamma==0.5.0
    - cleo==0.8.1
    - clikit==0.6.2
    - crashtest==0.3.1
    - cvxopt==1.2.5
    - cvxpy==1.1.7
    - dcmrtstruct2nii==1.0.19
    - dill==0.3.3
    - dm-tree==0.1.5
    - docopt==0.6.2
    - ecos==2.0.7.post1
    - flatbuffers==1.12
    - future==0.18.2
    - gast==0.4.0
    - gdcm==1.1
    - googleapis-common-protos==1.52.0
    - h5py==3.1.0
    - importlib-resources==4.1.1
    - lasagne==0.1
    - lifelines==0.25.6
    - multiprocess==0.70.11.1
    - nibabel==3.2.1
    - numexpr==2.7.2
    - opencv-python==4.5.1.48
    - opentsne==0.6.0
    - opt-einsum==3.3.0
    - osqp==0.6.2
    - pandas==1.1.4
    - pastel==0.2.1
    - progressbar==2.5
    - promise==2.3
    - pyarrow==2.0.0
    - pydicom==2.1.2
    - pydicom-seg==0.2.3
    - pykwalify==1.8.0
    - pylev==1.4.0
    - pyqt5==5.15.2
    - pyqt5-sip==12.8.1
    - pyradiomics==3.0.1
    - python-gdcm==3.0.9.0
    - pyyaml==5.3.1
    - qdldl==0.1.5.post0
    - random-survival-forest==0.8.0
    - ruamel-yaml==0.17.10
    - ruamel-yaml-clib==0.2.6
    - scikit-learn==0.22.2
    - scikit-survival==0.14.0
    - scs==2.1.2
    - simpleitk==2.0.2
    - sklearn==0.0
    - source==1.2.0
    - tabulate==0.8.9
    - tensorboard==2.4.1
    - tensorboard-logger==0.1.0
    - tensorflow==2.4.0rc0
    - tensorflow-determinism==0.3.0
    - tensorflow-gpu==2.4.0rc0
    - tensorflow-gpu-estimator==2.3.0
    - tensorflow-metadata==0.26.0
    - tensorflow-probability==0.12.1
    - tf-estimator-nightly==2.5.0.dev2021011701
    - tf-nightly-gpu==2.5.0.dev20210114
    - tfds-nightly==4.1.0.dev202101050107
    - theano==1.0.5
    - torch==1.7.1
    - tqdm==4.55.1
    - verstack==0.3.1
    - xgboost==1.4.2
