# Data
data:
  data_name: liverani

training:
  # Training
  eval_frequency: 200
  std_shape_generation: [-0, 0]  # minimum/maximum

  # Architecture
  inp_shape: 14
  latent_dim: 10
  num_clusters: 3
  activation: "sigmoid"
  type: "FC"
  monte_carlo: 1
  learn_prior: True

  # Optimization.
  loss_str: 'l2'
  regularization: 0 #0.0005
  dropout: 1
  learning_rate: 0.001
  decay_rate: 0.99
  momentum: 0 #0.9

  # Survival model
  weibull_shape: 2
  survival: True
  sample_surv: True