#!/usr/bin/env bash

# activate conda env
eval "$(conda shell.bash hook)"
conda activate Survival_Cluster_Analysis

python ./main_aft.py --data sim --seed 42 --penalty_weight 0.01
python ./main_aft.py --data sim --seed 73 --penalty_weight 0.01
python ./main_aft.py --data sim --seed 666 --penalty_weight 0.01
python ./main_aft.py --data sim --seed 777 --penalty_weight 0.01
python ./main_aft.py --data sim --seed 1009 --penalty_weight 0.01
