#!/usr/bin/env bash

# activate conda env
eval "$(conda shell.bash hook)"
conda activate Survival_Cluster_Analysis

python main_aft.py --data hemo --seed 42 --penalty_weight 0.01 --num_clusters 2
python main_aft.py --data hemo --seed 73 --penalty_weight 0.01 --num_clusters 2
python main_aft.py --data hemo --seed 666 --penalty_weight 0.01 --num_clusters 2
python main_aft.py --data hemo --seed 777 --penalty_weight 0.01 --num_clusters 2
python main_aft.py --data hemo --seed 1009 --penalty_weight 0.01 --num_clusters 2
python main_aft.py --data hemo --seed 1279 --penalty_weight 0.01 --num_clusters 2
python main_aft.py --data hemo --seed 1597 --penalty_weight 0.01 --num_clusters 2
python main_aft.py --data hemo --seed 1811 --penalty_weight 0.01 --num_clusters 2
python main_aft.py --data hemo --seed 1949 --penalty_weight 0.01 --num_clusters 2
python main_aft.py --data hemo --seed 2053 --penalty_weight 0.01 --num_clusters 2