# Data
data:
  data_name: MNIST

training:
  # Training
  eval_frequency: 200

  # Architecture
  inp_shape: 784
  latent_dim: 16
  activation: "sigmoid"
  monte_carlo: 1

  # Clustering model
  num_clusters: 5
  learn_prior: True

  # Survival model
  weibull_shape: 1
  survival: True
  sample_surv: True