# Data
data:
  data_name: nsclc

training:
  # Training
  eval_frequency: 200

  # Architecture
  inp_shape: [64, 64]
  n_slices: 11
  latent_dim: 32
  num_clusters: 4
  activation: "none"
  monte_carlo: 1
  learn_prior: True

  # Optimization
  learning_rate: 0.001
  decay_rate: 0.99
  momentum: 0

  # Survival model
  weibull_shape: 1
  survival: True
  sample_surv: False