# Data
data:
  data_name: sim

training:
  # Training
  eval_frequency: 200

  # Architecture
  inp_shape: 1000
  latent_dim: 16
  num_clusters: 3
  activation: "none"
  monte_carlo: 1
  learn_prior: True

  # Survival model
  weibull_shape: 1
  survival: True
  sample_surv: True