# Data
data:
  data_name: support

training:
  # Training
  eval_frequency: 200

  # Architecture
  inp_shape: 59
  latent_dim: 16
  num_clusters: 4
  activation: "none"
  monte_carlo: 1
  learn_prior: True

  # Optimization
  learning_rate: 0.001
  decay_rate: 0.99
  momentum: 0

  # Survival model
  weibull_shape: 2
  survival: True
  sample_surv: False